substitutions:
  _REGION: "us-central1"
  _AR_REPO: "microservices"
  _SERVICE_NAME: "auth-service"
  _PY_TEST_DIR: "test"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 0) (opcional) verifica docker
  - name: gcr.io/cloud-builders/docker
    args: ["version"]

  # 1) Lint con flake8 en venv (imagen de Python)
  - name: python:3.12
    entrypoint: bash
    args:
    - -lc
    - |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      [ -f requirements.txt ] && pip install -r requirements.txt
      pip install flake8
      echo ">> Running flake8 on app/ scripts/ test/"
      flake8 --config .flake8 app scripts test

  # 2) Tests con pytest en venv (misma imagen de Python)
  - name: python:3.12
    entrypoint: bash
    args:
      - -lc
      - |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -d "${_PY_TEST_DIR}" ]; then
          pip install pytest
          echo ">> Running pytest..."
          pytest -q
        else
          echo "No tests folder found, skipping tests."
        fi

  # 3) Build de la imagen
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
      - .

  # 4) Push a Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA

  # 5) Deploy a Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --cpu=1
      - --memory=512Mi
      - --max-instances=5
      - --min-instances=0
      - --port=8080

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA

timeout: "1800s"
